//Action Types

export enum ConnectionsTypes {
  LOAD_CONNECTIONS = '@Connections/LOAD_CONNECTIONS',
  UPDATE_CONNECTIONS = '@Connections/UPDATE_CONNECTIONS',
  DELETE_CONNECTIONS = '@Connections/DELETE_CONNECTIONS',
}

// UPDATE_SESSION

// UPDATE_CONTACTS
// LOAD_CONTACTS
// DELETE_CONTACT
// LOAD_CONTACTS

// LOAD_TICKETS
// RESET_UNREAD
// UPDATE_TICKET
// UPDATE_TICKET_UNREAD_MESSAGES
// UPDATE_TICKET_CONTACT
// DELETE_TICKET

// LOAD_QUEUES
// UPDATE_QUEUES
// DELETE_QUEUE

// LOAD_QUICK_ANSWERS
// UPDATE_QUICK_ANSWERS
// DELETE_QUICK_ANSWERS

// LOAD_USERS
// UPDATE_USERS
// DELETE_USER
